# kbox configuration for full-app
# This demonstrates all kbox features

apiVersion: kbox.dev/v1
kind: App

metadata:
  name: full-app

spec:
  # Image will be set by kbox up/deploy
  image: full-app:latest

  # Build configuration
  build:
    dockerfile: Dockerfile
    context: .

  # Application port
  port: 3000

  # Default replicas
  replicas: 2

  # Health check endpoint
  healthCheck: /health

  # Environment variables
  env:
    ENVIRONMENT: dev
    LOG_LEVEL: debug
    VERSION: "1.0.0"

  # Secrets from .env file
  secrets:
    fromEnvFile: .env

  # Resource limits
  resources:
    memory: 128Mi
    cpu: 100m

# Environment-specific overrides
environments:
  dev:
    replicas: 1
    env:
      ENVIRONMENT: dev
      LOG_LEVEL: debug

  staging:
    replicas: 2
    env:
      ENVIRONMENT: staging
      LOG_LEVEL: info

  prod:
    replicas: 3
    env:
      ENVIRONMENT: prod
      LOG_LEVEL: warn
    resources:
      memory: 256Mi
      cpu: 200m
